#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/automake-1.12.3.tar.xz -C /tmp 
echo "Successfully extract automake-1.12.3.tar.xz"
cd /tmp/automake-1.12.3
./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.12.3
make
make check
make install
cd /
rm -rf /tmp/*
