#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/bash-4.2.tar.gz -C /tmp 
echo "Successfully extract bash-4.2.tar.gz"
cd /tmp/bash-4.2
patch -Np1 -i /sources/bash-4.2-fixes-8.patch
./configure --prefix=/usr --bindir=/bin --htmldir=/usr/share/doc/bash-4.2 --without-bash-malloc --with-installed-readline
make
chown -Rv nobody .
su nobody -s /bin/bash -c "PATH=$PATH make tests"
make install
cd /
rm -rf /tmp/*
