#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/bison-2.6.2.tar.xz -C /tmp 
echo "Successfully extract bison-2.6.2.tar.xz"
cd /tmp/bison-2.6.2
./configure --prefix=/usr
echo '#define YYENABLE_NLS 1' >> lib/config.h
make
make check
make install
cd /
rm -rf /tmp/*
