#!/bin/bash
set -e
mkdir -p $LFS/etc/rc.d
cd $LFS/tmp
tar xvf $LFS/sources/lfs-bootscripts-20120725.tar.bz2 -C $LFS/tmp 
echo "Successfully extract lfs-bootscripts-20120725.tar.bz2"
cd $LFS/tmp/lfs-bootscripts-20120725
make install
cd /
rm -rf $LFS/tmp/*
