#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/gcc-4.7.1.tar.bz2 -C /tmp 
echo "Successfully extract gcc-4.7.1.tar.bz2"
cd /tmp/gcc-4.7.1
sed -i 's/install_to_$(INSTALL_DEST) //' libiberty/Makefile.in
case `uname -m` in
	i?86) sed -i 's/^T_CFLAGS =$/& -fomit-frame-pointer/' gcc/Makefile.in ;;
esac
sed -i -e /autogen/d -e /check.sh/d fixincludes/Makefile.in
mkdir -v ../gcc-build
cd ../gcc-build
../gcc-4.7.1/configure --prefix=/usr --libexecdir=/usr/lib --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-languages=c,c++ --disable-multilib --disable-bootstrap --with-system-zlib
make
ulimit -s 32768
make -k check || echo "Some tests will fail."
../gcc-4.7.1/contrib/test_summary || grep -A7 Summ
make install
ln -sv ../usr/bin/cpp /lib
ln -sv gcc /usr/bin/cc
echo 'main(){}' > dummy.c
cc dummy.c -v -Wl,--verbose &> dummy.log
readelf -l a.out | grep -q ': /lib'
grep -q -o '/usr/lib.*/crt[1in].*succeeded' dummy.log
grep -q -B4 '^ /usr/include' dummy.log
grep -q 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
grep -q "/lib.*/libc.so.6 " dummy.log
grep -q found dummy.log
rm -v dummy.c a.out dummy.log
mkdir -pv /usr/share/gdb/auto-load/usr/lib
mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib
cd /
rm -rf /tmp/*
