#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/grub-2.00.tar.xz -C /tmp 
echo "Successfully extract grub-2.00.tar.xz"
cd /tmp/grub-2.00
sed -i -e '/gets is a/d' grub-core/gnulib/stdio.in.h
./configure --prefix=/usr --sysconfdir=/etc --disable-grub-emu-usb --disable-efiemu --disable-werror
make
make install
cd /
rm -rf /tmp/*
