#!/tools/bin/bash
set -e
cd /tmp &&
grub-mkrescue --output=grub-img.iso &&
xorriso -as cdrecord -v dev=/dev/cdrw blank=as_needed grub-img.iso
grub-mkdevicemap --device-map=device.map
cat device.map
grub-install /dev/sdb
cat > /boot/grub/grub.cfg << "EOF"
# Begin /boot/grub/grub.cfg
set default=0
set timeout=5
insmod ext2
set root=(hd0,2)
menuentry "GNU/Linux, Linux 3.5.2-lfs-7.2" {
	linux
	/boot/vmlinuz-3.5.2-lfs-7.2 root=/dev/sda2 ro
}
EOF
cd /
rm -rf /tmp/*
