#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/inetutils-1.9.1.tar.gz -C /tmp 
echo "Successfully extract inetutils-1.9.1.tar.gz"
cd /tmp/inetutils-1.9.1
sed -i -e '/gets is a/d' lib/stdio.in.h
./configure --prefix=/usr --libexecdir=/usr/sbin --localstatedir=/var --disable-ifconfig --disable-logger --disable-syslogd --disable-whois --disable-servers
make
make check
make install
make -C doc html
make -C doc install-html docdir=/usr/share/doc/inetutils-1.9.1
mv -v /usr/bin/{hostname,ping,ping6} /bin
mv -v /usr/bin/traceroute /sbin
cd /
rm -rf /tmp/*
