#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/iproute2-3.5.1.tar.xz -C /tmp 
echo "Successfully extract iproute2-3.5.1.tar.xz"
cd /tmp/iproute2-3.5.1
sed -i '/^TARGETS/s@arpd@@g' misc/Makefile
sed -i /ARPD/d Makefile
sed -i 's/arpd.8//' man/man8/Makefile
make DESTDIR=
make DESTDIR= MANDIR=/usr/share/man DOCDIR=/usr/share/doc/iproute2-3.5.1 install
cd /
rm -rf /tmp/*
