#!/bin/bash
set -e
cd /tmp
tar xvf /sources/linux-3.5.2.tar.xz -C /tmp 
echo "Successfully extract linux-3.5.2.tar.xz"
cd /tmp/linux-3.5.2
make mrproper
cp /tmp2/.config /tmp/linux-3.5.2
make LANG=en_US.UTF-8 LC_ALL=
make
make modules_install
cp -v arch/x86/boot/bzImage /boot/vmlinuz-3.5.2-lfs-7.2
cp -v System.map /boot/System.map-3.5.2
cp -v .config /boot/config-3.5.2
install -d /usr/share/doc/linux-3.5.2
cp -r Documentation/* /usr/share/doc/linux-3.5.2
chown -R 0:0 /tmp/linux-3.5.2
install -v -m755 -d /etc/modprobe.d
cat > /etc/modprobe.d/usb.conf << "EOF"
# Begin /etc/modprobe.d/usb.conf
install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true
# End /etc/modprobe.d/usb.conf
EOF
cd /
#rm -rf $LFS/tmp/*
