#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/procps-3.2.8.tar.gz -C /tmp 
echo "Successfully extract procps-3.2.8.tar.gz"
cd /tmp/procps-3.2.8
patch -Np1 -i /sources/procps-3.2.8-fix_HZ_errors-1.patch
patch -Np1 -i /sources/procps-3.2.8-watch_unicode-1.patch
sed -i -e 's@\*/module.mk@proc/module.mk ps/module.mk@' Makefile
make
make install
cd /
rm -rf /tmp/*
