#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/tar-1.26.tar.bz2 -C /tmp 
echo "Successfully extract tar-1.26.tar.bz2"
cd /tmp/tar-1.26
sed -i -e '/gets is a/d' gnu/stdio.in.h
FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr --bindir=/bin --libexecdir=/usr/sbin
make
make check
make install
make -C doc install-html docdir=/usr/share/doc/tar-1.26
cd /
rm -rf /tmp/*
