#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/texinfo-4.13a.tar.gz -C /tmp 
echo "Successfully extract texinfo-4.13a.tar.gz"
cd /tmp/texinfo-4.13
./configure --prefix=/usr
make
make check
make install
make TEXMF=/usr/share/texmf install-tex
cd /usr/share/info
rm -v dir
for f in *
	do install-info $f dir 2>/dev/null
done

cd /
rm -rf /tmp/*
