#!/tools/bin/bash -x
set -e
cd /tmp
tar xvf /sources/vim-7.3.tar.bz2 -C /tmp 
echo "Successfully extract vim-7.3.tar.bz2"
cd /tmp/vim73
echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h
./configure --prefix=/usr --enable-multibyte
make
make test >/tmp/log 2>&1 || echo "Some errors with tests"
make install
ln -sv vim /usr/bin/vi
for L in /usr/share/man/{,*/}man1/vim.1; do
	ln -sv vim.1 $(dirname $L)/vi.1
done
ln -sv ../vim/vim73/doc /usr/share/doc/vim-7.3
cat > /etc/vimrc << "EOF"
" Begin /etc/vimrc
set nocompatible
set backspace=2
syntax on
if (&term == "iterm") || (&term == "putty")
	set background=dark
endif
" End /etc/vimrc
EOF
cd /
rm -rf /tmp/*
