#!/tools/bin/bash
set -e
cd /tmp
tar xvf /sources/zlib-1.2.7.tar.bz2 -C /tmp 
echo "Successfully extract zlib-1.2.7.tar.bz2"
cd /tmp/zlib-1.2.7
./configure --prefix=/usr
make
make check
make install
mv -v /usr/lib/libz.so.* /lib
ln -sfv ../../lib/libz.so.1.2.7 /usr/lib/libz.so
cd /
rm -rf /tmp/*
