#!/bin/bash
set -e
cd $LFS/tmp
tar xvf $LFS/sources/expect5.45.tar.gz -C $LFS/tmp 
echo "Successfully extract expect5.45.tar.gz"
cd $LFS/tmp/expect5.45
cp -v configure{,.orig}
sed 's:/usr/local/bin:/bin:' configure.orig > configure
./configure --prefix=/tools --with-tcl=/tools/lib --with-tclinclude=/tools/include
make
make test
make SCRIPTS="" install
cd /
rm -rf $LFS/tmp/*
