#!/bin/bash
set -e
cd $LFS/tmp
tar xvf $LFS/sources/file-5.11.tar.gz -C $LFS/tmp 
echo "Successfully extract file-5.11.tar.gz"
cd $LFS/tmp/file-5.11
./configure --prefix=/tools
make
make check
make install
cd /
rm -rf $LFS/tmp/*
