#!/bin/bash
set -e
cd $LFS/tmp
tar xvf $LFS/sources/gawk-4.0.1.tar.xz -C $LFS/tmp 
echo "Successfully extract gawk-4.0.1.tar.xz"
cd $LFS/tmp/gawk-4.0.1
./configure --prefix=/tools
make
make check
make install
cd /
rm -rf $LFS/tmp/*
