#!/bin/bash -x
set -E
cd $LFS/tmp
tar xvf $LFS/sources/glibc-2.16.0.tar.xz -C $LFS/tmp 
echo "Successfully extract glibc-2.16.0.tar.xz"
cd $LFS/tmp/glibc-2.16.0
if [ ! -r /usr/include/rpc/types.h ]; then
	su -c 'mkdir -p /usr/include/rpc'
	su -c 'cp -v sunrpc/rpc/*.h /usr/include/rpc'
fi
sed -i 's/ -lgcc_s//' Makeconfig
mkdir -v ../glibc-build
cd ../glibc-build 
../glibc-2.16.0/configure --prefix=/tools --host=$LFS_TGT --build=$(../glibc-2.16.0/scripts/config.guess) --disable-profile --enable-add-ons --enable-kernel=2.6.25 --with-headers=/tools/include libc_cv_forced_unwind=yes libc_cv_ctors_header=yes libc_cv_c_cleanup=yes
make
make install
echo 'main(){}' > dummy.c
$LFS_TGT-gcc dummy.c
readelf -l a.out | grep -q ': /tools'
ret=$?
if [ $ret -eq 0 ]; then
	echo "Compile test okay."
else
	exit 100
fi
cd /
rm -rf $LFS/tmp/*
