#!/bin/bash
set -e
cd $LFS/tmp
tar xvf $LFS/sources/m4-1.4.16.tar.bz2 -C $LFS/tmp 
echo "Successfully extract m4-1.4.16.tar.bz2"
cd $LFS/tmp/m4-1.4.16
sed -i -e '/gets is a/d' lib/stdio.in.h
./configure --prefix=/tools
make
make check
make install
cd /
rm -rf $LFS/tmp/*
