#!/bin/bash
set -e
cd $LFS/tmp
tar xvf $LFS/sources/make-3.82.tar.bz2 -C $LFS/tmp 
echo "Successfully extract make-3.82.tar.bz2"
cd $LFS/tmp/make-3.82
./configure --prefix=/tools
make
make check
make install
cd /
rm -rf $LFS/tmp/*
