#!/bin/bash
set -e
cd $LFS/tmp
tar xvf $LFS/sources/perl-5.16.1.tar.bz2 -C $LFS/tmp 
echo "Successfully extract perl-5.16.1.tar.bz2"
cd $LFS/tmp/perl-5.16.1
patch -Np1 -i $LFS/sources/perl-5.16.1-libc-2.patch
sh Configure -des -Dprefix=/tools
make
cp -v perl cpan/podlators/pod2man /tools/bin
mkdir -pv /tools/lib/perl5/5.16.1
cp -Rv lib/* /tools/lib/perl5/5.16.1
cd /
rm -rf $LFS/tmp/*
