#!/bin/bash
set -e
cd $LFS/tmp
tar xvf $LFS/sources/xz-5.0.4.tar.xz -C $LFS/tmp 
echo "Successfully extract xz-5.0.4.tar.xz"
cd $LFS/tmp/xz-5.0.4
./configure --prefix=/tools
make
make check 
make install
cd /
rm -rf $LFS/tmp/*
